// <auto-generated />
namespace RefWebApiOData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class penaltytypefix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(penaltytypefix));
        
        string IMigrationMetadata.Id
        {
            get { return "201610150231124_penaltytypefix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
